# fly.toml file generated for animodibs on 2023-04-16T21:25:04+08:00

app = "animodibs"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
